apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdeployment-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdeployment-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["myorg.io"]
    resources: ["appdeployments", "appdeployments/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appdeployment-operator-rb
subjects:
  - kind: ServiceAccount
    name: appdeployment-operator
roleRef:
  kind: ClusterRole
  name: appdeployment-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment-operator
  labels:
    app: appdeployment-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdeployment-operator
  template:
    metadata:
      labels:
        app: appdeployment-operator
    spec:
      serviceAccountName: appdeployment-operator
      containers:
        - name: operator
          image: your-docker-registry/appdeployment-operator:latest
          command: ["kopf", "run", "--namespace=default", "/operator/main.py"]
