apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appdeployments.myorg.io
spec:
  group: myorg.io
  names:
    kind: AppDeployment
    plural: appdeployments
    singular: appdeployment
    shortNames:
      - appd
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                image:
                  type: string
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                expose:
                  type: boolean
                checkIntervalSeconds:
                  type: integer
                  minimum: 1
              required:
                - replicas
                - image
                - port
                - checkIntervalSeconds
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
